import nodemailer from "nodemailer";
import type { ContactFormData } from "./types";

interface SendEmailOptions {
  subject: string;
  text: string;
  html: string;
}

export async function sendEmail({ subject, text, html }: SendEmailOptions): Promise<{ success: boolean; mode: "smtp" | "fallback"; info?: any }> {
  const host = process.env.SMTP_HOST;
  const port = process.env.SMTP_PORT ? parseInt(process.env.SMTP_PORT, 10) : 587;
  const secure = process.env.SMTP_SECURE === "true";
  const user = process.env.SMTP_USER;
  const pass = process.env.SMTP_PASS;
  const to = process.env.SMTP_TO || "leads@webixlinks.com";

  // Check if SMTP is configured
  if (!host || !user || !pass) {
    console.warn(
      "⚠️ SMTP email settings (SMTP_HOST, SMTP_USER, SMTP_PASS) are not configured. " +
      "Falling back to logging email content to console in development mode.\n" +
      `Subject: ${subject}\nTo: ${to}\nText:\n${text}`
    );
    return { success: true, mode: "fallback" };
  }

  const transporter = nodemailer.createTransport({
    host,
    port,
    secure,
    auth: {
      user,
      pass,
    },
  });

  const mailOptions = {
    from: `"Webixlinks Lead Engine" <${user}>`,
    to,
    subject,
    text,
    html,
  };

  try {
    const info = await transporter.sendMail(mailOptions);
    console.log("📨 Email sent successfully via SMTP:", info.messageId);
    return { success: true, mode: "smtp", info };
  } catch (error) {
    console.error("❌ Failed to send email via SMTP:", error);
    throw error;
  }
}

export function formatLeadEmail(data: ContactFormData) {
  const subject = `🚀 New Technical Brief from ${data.name} (${data.company})`;

  const text = `
New Technical Brief Submission:
------------------------------------------
Name: ${data.name}
Corporate Email: ${data.email}
Company: ${data.company}
Project Type: ${data.projectType || "Not Specified"}

Project Overview:
${data.message || "No description provided."}
------------------------------------------
NDA Requested: Yes (Default)
  `;

  const html = `
    <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e4e4e7; rounded-corners: 8px;">
      <h2 style="color: #ef4444; margin-bottom: 20px; border-bottom: 2px solid #ef4444; padding-bottom: 10px;">New Lead: Technical Brief</h2>
      <table style="width: 100%; border-collapse: collapse; margin-bottom: 20px;">
        <tr>
          <td style="padding: 8px 0; font-weight: bold; border-bottom: 1px solid #f4f4f5; width: 140px;">Name</td>
          <td style="padding: 8px 0; border-bottom: 1px solid #f4f4f5;">${data.name}</td>
        </tr>
        <tr>
          <td style="padding: 8px 0; font-weight: bold; border-bottom: 1px solid #f4f4f5;">Email</td>
          <td style="padding: 8px 0; border-bottom: 1px solid #f4f4f5;"><a href="mailto:${data.email}">${data.email}</a></td>
        </tr>
        <tr>
          <td style="padding: 8px 0; font-weight: bold; border-bottom: 1px solid #f4f4f5;">Company</td>
          <td style="padding: 8px 0; border-bottom: 1px solid #f4f4f5;">${data.company}</td>
        </tr>
        <tr>
          <td style="padding: 8px 0; font-weight: bold; border-bottom: 1px solid #f4f4f5;">Project Type</td>
          <td style="padding: 8px 0; border-bottom: 1px solid #f4f4f5;"><span style="background: #fee2e2; color: #991b1b; padding: 2px 8px; border-radius: 4px; font-size: 0.85em; font-weight: bold;">${data.projectType}</span></td>
        </tr>
      </table>
      <div style="background: #f8fafc; border: 1px solid #e2e8f0; padding: 15px; border-radius: 6px; margin-bottom: 20px;">
        <h4 style="margin-top: 0; color: #334155;">Project Overview:</h4>
        <p style="white-space: pre-wrap; line-height: 1.6; color: #475569; margin-bottom: 0;">${data.message || "<em>No project description provided.</em>"}</p>
      </div>
      <p style="font-size: 0.8em; color: #71717a; margin-top: 30px; text-align: center; border-top: 1px solid #e4e4e7; padding-top: 15px;">
        This email was automatically generated by Webixlinks Lead Engine.
      </p>
    </div>
  `;

  return { subject, text, html };
}
